import "@/devlink/global.css";
import "./globals.css";
import type { Metadata } from "next";
import { DevLinkProvider } from "@/devlink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
      <DevLinkProvider>
        {children}
      </DevLinkProvider>
    </body>
  </html>
  );
}
